#!/usr/bin/env ruby

# This script runs your testing suite. For a typical Ruby project running
# test-unit this is probably all you need.

# rake

if status = ENV['COPY_STATUS']
  require 'fileutils'
  FileUtils.cp(status, status + '.test')
end

STDOUT.puts "Some valid test results. No fails."
STDERR.puts ""

exit(0)
